const {test}=require('node:test');
const assert=require('node:assert/strict');
const {FishingGame,species}=require('../game/engine.js');
function hooked(type=0){const g=new FishingGame(()=>.5);g.fish=[{...species[type],x:575,y:260,dir:1,speed:0}];g.action();for(let i=0;i<100&&g.state==='casting';i++)g.update(.02);assert.equal(g.state,'reeling');return g;}
test('aim is limited to 20 degrees on both sides and changes hook position',()=>{const g=new FishingGame();g.aim(100);assert.equal(g.angle,20);g.depth=200;assert.ok(g.hook().x>575);g.aim(-200);assert.equal(g.angle,-20);assert.ok(g.hook().x<575);});
test('collision hooks a fish; three second grace period precedes line failure',()=>{const g=hooked();g.update(3);assert.equal(g.strength,100);g.update(5);assert.equal(g.state,'lost');assert.equal(g.message,'YOU LOST THE FISH TRY AGAIN!');g.action();assert.equal(g.state,'casting');});
test('each fish can be landed at its advertised tap rate and awards points once',()=>{for(let type=0;type<4;type++){const g=hooked(type);g.update(3);for(let i=0;i<100&&g.state==='reeling';i++){g.action();g.update(1/species[type].rate);}assert.equal(g.state,'landed');assert.equal(g.score,species[type].points);assert.equal(g.caught,1);assert.equal(g.fish.length,1);g.action();assert.equal(g.score,species[type].points);}});
test('larger fish demand faster taps',()=>{const small=hooked(0),large=hooked(3);for(const g of [small,large]){g.update(3);for(let i=0;i<30&&g.state==='reeling';i++){g.action();g.update(.5);}}assert.equal(small.state,'landed');assert.equal(large.state,'lost');});
test('empty cast retrieves hook and allows another cast',()=>{const g=new FishingGame();g.fish=[];g.action();for(let i=0;i<600;i++)g.update(.02);assert.equal(g.state,'missed');assert.equal(g.depth,0);g.action();assert.equal(g.state,'casting');});
test('host serves game entry points and assets but not arbitrary game files',async t=>{const {createServer}=require('../server.cjs');const s=createServer({fishService:async()=>({status:200,data:{}})});await new Promise(r=>s.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>s.close(r)));const base=`http://127.0.0.1:${s.address().port}`;for(const path of ['/game','/game/','/game/index.html','/game/game.css','/game/game.js','/game/engine.js'])assert.equal((await fetch(base+path)).status,200,path);assert.equal((await fetch(base+'/game/private.json')).status,404);});
